-- Create the Database 
CREATE DATABASE Showroom;
USE Showroom;

-- Import Datasets : Cars, Customers, Sales & Analyze the Fact table and Dimension table. 

SELECT * FROM sales LIMIT 5;
/*
	Result :
    SALE_ID | CUSTOMER_ID | CAR_ID | SALE_DATE  | QUANTITY | SALE_PRICE | PAYMENT_METHOD | SALESPERSON   | 
    
    S00001	| CU1241	  | C0214  | 2025-03-28 |	3	   | 73293.19	| Installment	 | Ashley Ramos  |
	S00002	| CU0100	  | C0202  | 2024-02-12 |	3	   | 32681.2	| Cash			 | Pamela Blair  |
	S00003	| CU1690	  | C0228  | 2023-02-26 |	2	   | 53530.92	| Credit	     | Sergio Lee    |
	S00004	| CU0534	  | C0231  | 2024-06-21 |	1	   | 89816.61	| Cash		     | Mary Johnston |
	S00005	| CU1153	  | C0071  | 2023-12-21 |	2	   | 77590.86	| Installment	 | Ricardo Garcia|
*/

SELECT * FROM cars LIMIT 5;
/* 
	Result :
    CAR_ID | BRAND   | MODEL   | YEAR | COLOUR| ENGINE_TYPE|TRANSMISSION|  PRICE   |QUANTITY| STATUS    |

    C0001  | Toyota	 | Camry   | 2023 |	Red	  | Petrol	   | Automatic	| 80338.15 |   6	| Available |
	C0002  | Tesla	 | Model 3 | 2019 |	Red	  | Electric   | Manual	    | 26437.73 |   16	| Available |
	C0003  | Nissan	 | Qashqai | 2018 |	Blue  |	Electric   | Automatic	| 50158.13 |   20	| Available |
	C0004  | Hyundai | Sonata  | 2025 |	Red	  | Hybrid	   | Automatic	| 33026.14 |   3	| Available |
	C0005  | Toyota	 | RAV4	   | 2016 |	White |	Hybrid	   | Manual	    | 79672.9  |   9	| Reserved  |
*/

SELECT * FROM Customers LIMIT 5;
/* 
	Result :
	CUSTOMER_ID | NAME 				| GENDER |AGE | PHONE 			| EMAIL 					| CITY 				|
    
    CU0001		| Jill Snyder		| Male	 | 49 | (527)170-6357	| timothy92@yahoo.com		| Juliabury			|
	CU0002		| Nicholas Foster	| Male	 | 23 | 324-959-9856x281| cochrancarlos@berry.info	| Wrightport		|
	CU0003		| Courtney Robbins	| Male	 | 60 | 461.428.6407	| donna01@yahoo.com			| Lake Zacharyburgh	|
	CU0004		| Blake Barry		| Male	 | 67 | 119-340-1448x571| sandra08@yahoo.com		| Ramirezburgh		|
	CU0005		| Claudia Hardin	| Female | 31 | 514-684-2974x378| caitlindavis@bradley.org	| Lake Tamara		|
*/

-- DATA CLEANING PROCESS 
--  Check Null Values -> Using COUNT

SELECT COUNT(*) AS Sales_Null FROM sales 
WHERE Sale_ID IS NULL
   OR Customer_ID IS NULL
   OR Car_ID IS NULL
   OR Sale_Date IS NULL
   OR Quantity IS NULL
   OR Sale_Price IS NULL
   OR Payment_Method IS NULL
   OR Salesperson IS NULL;
   
SELECT COUNT(*) AS Cars_Null FROM Cars 
WHERE Car_ID IS NULL
   OR Brand IS NULL
   OR Model IS NULL
   OR Year IS NULL
   OR color IS NULL
   OR Engine_Type IS NULL
   OR Transmission IS NULL
   OR Price IS NULL
   OR Quantity_In_Stock IS NULL
   OR Status IS NULL;
   
   -- If you want column wise null values
SELECT 
	SUM(CASE WHEN Customer_ID IS NULL THEN 1 ELSE 0 END ) AS Customer_ID,
    SUM(CASE WHEN Name IS NULL THEN 1 ELSE 0 END ) AS Name,
    SUM(CASE WHEN Gender IS NULL THEN 1 ELSE 0 END ) AS Gender,
    SUM(CASE WHEN Age IS NULL THEN 1 ELSE 0 END ) AS Age,
    SUM(CASE WHEN Phone IS NULL THEN 1 ELSE 0 END ) AS Phone,
    SUM(CASE WHEN Email IS NULL THEN 1 ELSE 0 END ) AS Email,
    SUM(CASE WHEN City IS NULL THEN 1 ELSE 0 END ) AS City
FROM Customers;
    
-- Check duplicates.

SELECT Customer_ID, COUNT(*) AS Duplicate_Count
FROM Customers
GROUP BY Customer_ID
HAVING COUNT(*) > 1;

SELECT Sale_ID , count(*) AS Duplicate_Count
FROM sales
GROUP BY sale_ID
HAVING COUNT(*) > 1;

SELECT car_ID , count(*) AS Duplicate_Count
FROM cars
GROUP BY car_ID
HAVING COUNT(*) > 1;

-- Change the Sale_Date datatype ( text -> date)

ALTER TABLE Sales ADD COLUMN Sale_Date_New DATE;

UPDATE Sales
SET Sale_Date_New = STR_TO_DATE(Sale_Date, '%Y-%m-%d');

ALTER TABLE Sales DROP COLUMN Sale_Date;
ALTER TABLE Sales CHANGE Sale_Date_New Sale_Date DATE;

DESCRIBE SALES;

--  ANALYSIS PROCESS

-- Total Revenue Generated by Each Car Brand

SELECT 
	C.Brand ,
    Floor(SUM(S.Sale_Price * S.Quantity)) AS Total_Revenue
FROM Sales As S
LEFT JOIN CARS AS C ON S.car_ID = C.car_ID
GROUP BY C.Brand 
ORDER BY Total_Revenue DESC;

-- Yearly Sales Performance

SELECT 
    YEAR(S.Sale_Date) AS Year,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS Total_Revenue
FROM Sales AS S
GROUP BY YEAR(S.Sale_Date)
ORDER BY Year;

-- Total stock value per status

SELECT 
    Status,
    SUM(Quantity_In_Stock) AS Total_Stock,
    FLOOR(SUM(Price * Quantity_In_Stock)) AS Total_Amount
FROM Cars
GROUP BY Status
ORDER BY Total_Stock DESC;

-- Mostly Used Payment Method

SELECT 
    S.Payment_Method,
    COUNT(*) AS Total_Transactions
FROM Sales S
GROUP BY S.Payment_Method
ORDER BY Total_Transactions DESC;

-- Transmission Type Sales Comparison

SELECT 
    C.Transmission,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS Total_Revenue
FROM Cars AS C
JOIN Sales AS S ON C.Car_ID = S.Car_ID
GROUP BY C.Transmission
ORDER BY Total_Revenue DESC;

-- Top 3 Best-Selling Car Model

SELECT 
	C.Brand ,
	C.Model ,
    Floor(SUM(S.Sale_Price * S.Quantity)) AS Best_Selling
FROM cars AS C
LEFT JOIN sales AS S ON C.car_ID = S.car_ID
GROUP BY C.Brand,C.Model
ORDER BY Best_Selling DESC
LIMIT 3;

-- Top 5 Customers Who Spent the Most

SELECT 
	U.Customer_ID ,
    U.Name ,
    Floor(SUM(S.Sale_Price * S.Quantity)) AS Best_Customers
FROM Customers AS U 
LEFT JOIN Sales AS S ON U.Customer_ID = S.Customer_ID
GROUP BY U.Customer_ID,U.Name
ORDER BY Best_Customers DESC
LIMIT 5;

-- Total Monthly Sales 

SELECT 
    MONTHNAME(S.Sale_Date) AS Month,
    Floor(SUM(S.Sale_Price * S.Quantity)) AS Total_Revenue
FROM Sales S
GROUP BY  MONTHNAME(S.Sale_Date)
ORDER BY  FIELD(Month,
    'January','February','March','April','May','June',
    'July','August','September','October','November','December');
    
-- Top 10 Customer Loyalty Analysis

SELECT 
    Cu.Customer_ID,
    Cu.Name,
    COUNT(S.Sale_ID) AS Total_Purchases,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS Total_Spent
FROM Customers AS Cu
JOIN Sales AS S ON Cu.Customer_ID = S.Customer_ID
GROUP BY Cu.Customer_ID, Cu.Name
ORDER BY Total_Spent DESC
LIMIT 10;

-- Top 10 City-wise Customer Revenue Contribution

SELECT 
    C.City,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS City_Revenue
FROM Customers AS C
JOIN Sales AS S ON C.Customer_ID = S.Customer_ID
GROUP BY C.City
ORDER BY City_Revenue DESC
LIMIT 10;

-- Total Sales by Day of the Week

SELECT 
    DAYNAME(S.Sale_Date) AS Day_Name,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS Total_Revenue
FROM Sales AS S
GROUP BY Day_Name
ORDER BY Total_Revenue DESC;

-- Monthly Average Quantity Sold

SELECT 
    MONTHNAME(S.Sale_Date) AS Month,
    Floor(SUM(S.Quantity*S.Sale_Price)) AS Total_Amount
FROM Sales AS S
GROUP BY MONTHNAME(S.Sale_Date)
ORDER BY FIELD(Month,
    'January','February','March','April','May','June',
    'July','August','September','October','November','December');

-- Age Group-wise Sales Contribution

SELECT 
    CASE
        WHEN C.Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN C.Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN C.Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS Age_Group,
    COUNT(C.Customer_ID) AS Customers,
    FLOOR(SUM(S.Sale_Price * S.Quantity)) AS Total_Spent
FROM Customers AS C
JOIN Sales AS S ON C.Customer_ID = S.Customer_ID
GROUP BY Age_Group
ORDER BY Total_Spent DESC;




	





